"""
Data models for the DownTime Weekend Email Digest Agent.

Extends the core Event model from the backend with email-specific grouping
and categorization structures.
"""

from dataclasses import dataclass, field
from typing import Optional
from pydantic import BaseModel, Field
from datetime import datetime


# ── Agent-side Event model ────────────────────────────────────────────────────
# The agent maintains its own Event model for email-specific fields
# (email_category, why_go). Backend models are imported from the
# downtime-backend package installed as a dependency.


class Event(BaseModel):
    """Mirror of the backend Event model — kept in sync manually."""

    id: str
    title: str
    description: str = ""
    category: str = ""
    scenario: str = ""
    source: str
    source_url: str = ""
    venue: str = ""
    address: str = ""
    city: str = ""
    state: str = ""
    lat: float = 0.0
    lon: float = 0.0
    date_start: Optional[str] = None
    date_end: Optional[str] = None
    time_info: str = ""
    price_range: str = ""
    price_note: str = ""
    image_url: Optional[str] = None
    camera_worthy: bool = False
    camera_note: Optional[str] = None
    tags: list[str] = Field(default_factory=list)
    score: int = 0
    is_featured: bool = False
    created_at: datetime = Field(default_factory=datetime.utcnow)

    # ── Email-only enrichment ──────────────────────────────────────────────────
    why_go: str = ""  # 1-2 sentence pitch generated by curator
    email_category: str = ""  # "Date Night", "Adventure/Outdoors", etc.


# ── Email grouping ─────────────────────────────────────────────────────────────

EMAIL_CATEGORIES = [
    "Date Night",
    "Adventure / Outdoors",
    "Food & Drink",
    "Arts & Culture",
    "Free Things",
]

# Maps DownTime category + scenario → email category
CATEGORY_BUCKET_MAP: dict[tuple[str, str], str] = {
    # (downtime_category, scenario) → email_category
    ("food", "date-night"): "Date Night",
    ("nightlife", "date-night"): "Date Night",
    ("music", "date-night"): "Date Night",
    ("arts", "date-night"): "Date Night",
    ("film", "date-night"): "Date Night",
    ("outdoor", "weekend-adventure"): "Adventure / Outdoors",
    ("outdoor", "solo"): "Adventure / Outdoors",
    ("outdoor", "travel"): "Adventure / Outdoors",
    ("sports", "weekend-adventure"): "Adventure / Outdoors",
    ("motorsports", "weekend-adventure"): "Adventure / Outdoors",
    ("festivals", "weekend-adventure"): "Adventure / Outdoors",
    ("food", "solo"): "Food & Drink",
    ("food", "weekend-adventure"): "Food & Drink",
    ("food", "travel"): "Food & Drink",
    ("arts", "solo"): "Arts & Culture",
    ("arts", "travel"): "Arts & Culture",
    ("arts", "weekend-adventure"): "Arts & Culture",
    ("photography", "solo"): "Arts & Culture",
    ("photography", "travel"): "Arts & Culture",
    ("film", "solo"): "Arts & Culture",
}

# Fallback category map by DownTime category only
CATEGORY_FALLBACK_MAP: dict[str, str] = {
    "music": "Date Night",
    "nightlife": "Date Night",
    "film": "Arts & Culture",
    "arts": "Arts & Culture",
    "photography": "Arts & Culture",
    "food": "Food & Drink",
    "festivals": "Adventure / Outdoors",
    "outdoor": "Adventure / Outdoors",
    "sports": "Adventure / Outdoors",
    "motorsports": "Adventure / Outdoors",
}


@dataclass
class CuratedWeekend:
    """The final curated set of events for the weekend email."""

    fetch_date: datetime
    weekend_start: str  # e.g. "Friday, Jan 17"
    weekend_end: str  # e.g. "Sunday, Jan 19"
    city_label: str  # e.g. "Dallas–Fort Worth"
    buckets: dict[str, list[Event]] = field(default_factory=dict)
    total_fetched: int = 0
    total_scored: int = 0

    @property
    def all_events(self) -> list[Event]:
        events = []
        for evts in self.buckets.values():
            events.extend(evts)
        return events
